#ifndef ADC_INTERFACE_H
#define ADC_INTERFACE_H


typedef enum
{
	ADC0_SINGLE_ENDED=0,
	ADC1_SINGLE_ENDED,
	ADC2_SINGLE_ENDED,
	ADC3_SINGLE_ENDED,
	ADC4_SINGLE_ENDED,
	ADC5_SINGLE_ENDED,
	ADC6_SINGLE_ENDED,
	ADC7_SINGLE_ENDED,
	ADC0_POS_ADC0_NEG_10x_GAIN,
	ADC1_POS_ADC0_NEG_10x_GAIN,
	ADC0_POS_ADC0_NEG_200x_GAIN,
	ADC1_POS_ADC0_NEG_200x_GAIN,
	ADC2_POS_ADC2_NEG_10x_GAIN,
	ADC3_POS_ADC2_NEG_10x_GAIN,
	ADC2_POS_ADC2_NEG_200x_GAIN,
	ADC3_POS_ADC2_NEG_200x_GAIN,
	ADC0_POS_ADC1_NEG_1x_GAIN,
	ADC1_POS_ADC1_NEG_1x_GAIN,
	ADC2_POS_ADC1_NEG_1x_GAIN,
	ADC3_POS_ADC1_NEG_1x_GAIN,
	ADC4_POS_ADC1_NEG_1x_GAIN,
	ADC5_POS_ADC1_NEG_1x_GAIN,
	ADC6_POS_ADC1_NEG_1x_GAIN,
	ADC7_POS_ADC1_NEG_1x_GAIN,
	ADC0_POS_ADC2_NEG_1x_GAIN,
	ADC1_POS_ADC2_NEG_1x_GAIN,
	ADC2_POS_ADC2_NEG_1x_GAIN,
	ADC3_POS_ADC2_NEG_1x_GAIN,
	ADC4_POS_ADC2_NEG_1x_GAIN,
	ADC5_POS_ADC2_NEG_1x_GAIN
}ADC_Channel_t;

void ADC_voidInit(void);
uint8 ADC_u8GetChannelReading (ADC_Channel_t copy_u8Channel);

#endif
